run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    # Default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # Manually enabled
    - gocyclo
    - gofmt
    - goprintffuncname
    - misspell
    - prealloc
    - revive
    - unconvert
    - whitespace
linters-settings:
  govet:
    # Report about shadowed variables
    check-shadowing: true
issues:
  exclude-use-default: false
  exclude:
    # govet: Common false positives
    - (possible misuse of unsafe.Pointer|should have signature)
